### ISSUE TITLE
Install a build management tool

### ISSUE THREAD

**Issue by hargitomi97** [BME-MIT-IET/undefined-iet-2019#4]
Currenty, we don't have a build management tool installed to our project.

**Fix:** install an appropriate tool.

**Comment by kripod** [comment]
A build procedure is already in place as a set of [`package.json`](https://github.com/BME-MIT-IET/undefined-iet-2019/blob/0c4972103364486136ecc3f4892b47226609f53a/package.json#L25-L27) scripts.
